for raspberry

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,6 +1,17 @@
 # Handle ros distro
+
 ARG ROS_DISTRO=noetic
-FROM ghcr.io/aica-technology/ros-ws:${ROS_DISTRO}
+ARG BASE_TAG=noetic
+FROM ros:${BASE_TAG} as environment-variables
+ENV DEBIAN_FRONTEND=noninteractive
+ENV PIP_NO_CACHE_DIR 1
+ENV USER ros
+ENV HOME /home/${USER}
+ENV ROS_WORKSPACE /home/${USER}/ros_ws
+ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
+
+FROM environment-variables as base-dependencies
+
 
 # User provided arguments
 ARG HOST_GID=1000
@@ -15,12 +26,19 @@ SHELL ["/bin/bash", "-c"]
 # AICA uses the same name for user and user group
 ENV USER_GROUP=${USER}
 USER root
-RUN if [ "HOST_GID" != "1000"] ; \
-    then groupadd --gid ${HOST_GID} host_group && \
-    usermod ${USER} -g ${HOST_GID} && \ 
-    usermod ${USER} -a -G ${USER_GROUP}; fi
-USER ${USER}
+# create and configure a new user
+ARG UID=1000
+ARG GID=1000
+RUN addgroup --gid ${GID} ${USER}
+RUN adduser --gecos "ROS User" --uid ${UID} --gid ${GID} ${USER} && yes | passwd ${USER}
+RUN usermod -a -G dialout ${USER}
+RUN usermod -a -G tty ${USER}
+RUN echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/99_aptget
+RUN chmod 0440 /etc/sudoers.d/99_aptget && chown root:root /etc/sudoers.d/99_aptget
 
+USER ${USER}
+RUN sudo apt update
+RUN sudo apt install git -y
 # Setup git identity
 RUN git config --global user.name "${GIT_NAME}"
 RUN git config --global user.email "${GIT_EMAIL}"
@@ -40,15 +58,25 @@ RUN sudo apt-get update && sudo apt-get install -y \
     alsa-utils \
     netbase \
     ros-noetic-vrpn-client-ros \
-    ros-${ROS_DISTRO}-ros-control \
-    ros-${ROS_DISTRO}-ros-controllers \
+    ros-noetic-ros-control \
+    ros-noetic-ros-controllers \
     ros-noetic-diagnostic-updater \
     ros-noetic-mavros* \
     dbus-x11 \
     libcanberra-gtk-module libcanberra-gtk3-module \
     gnome-terminal \
+    build-essential \
+    mesa-common-dev \
+    libqt5opengl5 \
+    freeglut3-dev \
+    libbluetooth-dev \
+    qtbase5-dev \
+    qtconnectivity5-dev \
     && sudo apt-get upgrade -y && sudo apt-get clean
 
+
+#    ros-noetic-openzen-sensor \
+#    libspdlog-dev \
 
 # Handle SIMD option
 RUN if [ "${USE_SIMD}" = "ON" ] ; \ 
@@ -59,11 +87,12 @@ RUN sudo ldconfig
 RUN rm -rf /tmp/*
 
 # Install workspace
-WORKDIR /home/${USER}
+WORKDIR /home/${USER}/ros_ws
 RUN git clone https://github.com/bonato47/robetarme_record_ws.git
-RUN cp -r robetarme_record_ws/* ros_ws
+RUN cp -r robetarme_record_ws/* .
 RUN rm -rf robetarme_record_ws
-
+WORKDIR /home/${USER}/ros_ws/src
+RUN git clone --recurse-submodules https://bitbucket.org/lpresearch/openzenros.git
 ### Add environement variables to bashrc
 WORKDIR /home/${USER}
 
@@ -74,12 +103,24 @@ RUN sudo chown -R ${USER}:${HOST_GID} .bashrc
 # Add cmake option to bash rc if needed
 RUN if [ "${USE_SIMD}" = "ON" ] ; \
     then echo "export ENABLE_SIMD=ON" >> /home/${USER}/.bashrc ; fi
+RUN sudo apt install bluez
+RUN sudo service dbus start
+RUN sudo service bluetooth start
+
 
 ### Build ros workspace
+USER ${USER}
 WORKDIR /home/${USER}/ros_ws
+RUN rosdep update
 RUN source /opt/ros/noetic/setup.bash && rosdep install --from-paths src --ignore-src -r -y
-RUN pushd src/xsens_ros_mti_driver/lib/xspublic && make && popd
-RUN source /opt/ros/noetic/setup.bash  && catkin_make;
+#RUN sudo chmod -R o+rw src/xsens_ros_mti_driver *
+#RUN pushd src/xsens_ros_mti_driver/lib/xspublic && make && popd
+#RUN rm src/xsens_ros_mti_driver -r
 
+
+
+RUN source /opt/ros/noetic/setup.bash && catkin_make -DZEN_BLUETOOTH=ON || echo "fail_catkin";
+
+#RUN source devel/setup.bash
 ### Final apt clean
 RUN sudo apt update && sudo apt upgrade && sudo apt clean
